stages:

  - stage: Build
    displayName: 'Build Stage'
    jobs:
      - job: Build
        displayName: 'Install Dependencies'
        pool:
          name: 'ksolanki6269_pool' 
        steps:
          - task: NodeTool@0
            inputs:
              versionSpec: '18.x'
            displayName: 'Use Node.js'
          
          - script: npm install
            displayName: 'Install Dependencies'

  - stage: Test
    displayName: 'Test Stage'
    jobs:
      - job: Test
        displayName: 'Run Unit Tests'
        pool:
          name: 'ksolanki6269_pool' 
        steps:
          - script: npm test
            displayName: 'Run Tests with Jest'

  - stage: Deploy
    displayName: 'Deploy Stage'
    jobs:
      - deployment: DeployFunction
        displayName: 'Deploy to Azure Function App'
        environment: production
        pool:
          name: 'ksolanki6269_pool' 
        strategy:
          runOnce:
            deploy:
              steps:
                - task: ArchiveFiles@2
                  displayName: 'Archive function app files'
                  inputs:
                    rootFolderOrFile: '$(Build.SourcesDirectory)'  # Your function app root directory
                    includeRootFolder: false
                    archiveFile: '$(Build.ArtifactStagingDirectory)/function.zip'
                    verbose: true

                - task: AzureFunctionApp@1
                  displayName: 'Deploy Function to Azure'
                  inputs:
                    azureSubscription: 'ksolanki6269_lab5'
                    appType: 'functionApp'
                    appName: 'ksolankiHttpTriggerFunction'
                    package: '$(Build.ArtifactStagingDirectory)/function.zip'  # Deploy ZIP file